services:
  backend:
    container_name: backend
    build:
      context: ./pokemon-trainer-api
      dockerfile: DockerFile
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=dev
      - JWT_SECRET=pokemontrainer
      - DATABASE_URL=postgresql://docker:docker@database:5432/apipokemontrainer?schema=public
    volumes:
      - backend-data:/app
      - ./pokemon-trainer-api/src:/app/src
    networks:
      - app-network

  database:
    container_name: database
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apipokemontrainer
    volumes:
      - database-data:/bitnami/postgresql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
  database-data:
