FROM node:latest AS build

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./

RUN npm install

COPY . .

RUN npm install --save-dev @types/node

RUN npm install typescript && npm install vite --save-dev

EXPOSE 5173

CMD ["npm", "run", "dev"]